version: "3"

# A docker-compose file to start the application in native mode.

services:
  api_jvm:
    network_mode: bridge
    build:
      dockerfile: ../docker/Dockerfile.native
      context: ../machi-todo-api
    ports:
      - 8080:8080
    env_file:
      - docker.env