version: "3"
# a docker-compose file to start the application in jvm mode
services:
  api_jvm:
    network_mode: bridge
    build:
      dockerfile: ../docker/Dockerfile.jvm
      context: ../machi-todo-api
    ports:
      - 8080:8080
    env_file:
      - docker.env