version: "3"

services:
  api_jvm: # to start the application in jvm mode
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: ../machi-todo-api
    ports:
      - 8080:8080
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5432/todo-db
      - QUARKUS_DATASOURCE_USERNAME=todo-api-user
      - QUARKUS_DATASOURCE_PASSWORD=todo-api-pwd
    depends_on:
      - db
      - keycloak
    networks:
      - storage

  keycloak:
    image: quay.io/keycloak/keycloak:7.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - storage
    ports:
      - 8180:8080

  db:
    image: postgres
    container_name: todo_api_db
    environment:
      - POSTGRES_USER=todo-api-user
      - POSTGRES_PASSWORD=todo-api-pwd
      - POSTGRES_DB=todo-db
    networks:
      - storage

networks:
  storage:
    driver: bridge